### PR TITLE
#4 Outline/Timestamps for "Intro to TypeScript and Angular 5"

### PR DESCRIPTION
**Pull request by sbibow**

### CODE REVIEW

**Comment by sbibow** [comment]
Things that still need work:
- everything after 1 hour
  - more captions / topics
- general refactoring
  - verify timestamps
  - shorten topic description
  - remove unnecessary topics

**Comment by sbibow** [comment]
@w3cj Is it a good idea to have a section "Important Links"?

**Comment by sbibow** [comment]
Resolved WIP

@w3cj This is now ready to merge 💪

**Comment by w3cj** [comment]
THANK YOU!!! 🎉

**Pull request merged**
